# Generated by Django 5.1.1 on 2024-09-25 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stock",
            name="price_at_date",
        ),
        migrations.AddField(
            model_name="stock",
            name="symbol",
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
